name: Generate Gallery Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate data.json from /images recursively
        run: |
          echo "[" > data.json
          find images -type f -name "*.png" | sort | sed 's|^images/||' | awk '{ printf "  {\"file\": \"%s\"},\n", $0 }' >> data.json
          sed -i '$ s/,$//' data.json
          echo "]" >> data.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data.json
          git commit -m "Auto-update gallery with folders" || echo "No changes"
          git push
